"""altera descricao de categoria para string

Revision ID: 8db5527f3eac
Revises: 85fefe53fbbd
Create Date: 2026-09-11 20:30:55.842979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8db5527f3eac'
down_revision: Union[str, Sequence[str], None] = '85fefe53fbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorias', 'descricao',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorias', 'descricao',
               existing_type=sa.String(length=255),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
